# Add 'enhancement' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
enhancement:
  - head-branch: ["^feature/"]

bug:
  - head-branch: ["^fix/"]

internal:
  - head-branch: ["^chore/"]
